name: CI/CD Pileline for NDSL PAN Verification 

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    name: Build & Deploy
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Build with Maven
      run: mvn -B package --file pom.xml
    - name: Build & push Docker image
      uses: mr-smithers-excellent/docker-build-push@v5
      with:
        registry: co-repo
        image: app/co-repo
        dockerfile: Dockerfile  

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-south-1  
        
    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1    
      
    - name: Build, tag, and push image to Amazon ECR
      id: build-image
      env:
        ECR_REGISTRY: 654400775970.dkr.ecr.ap-south-1.amazonaws.com
        ECR_REPOSITORY: co-repo
        IMAGE_TAG: latest 
      run: |
          # Build a docker container and push it to ECR 
          docker build -t 654400775970.dkr.ecr.ap-south-1.amazonaws.com/co-repo:latest .
          echo "Pushing image to ECR..."
          docker push 654400775970.dkr.ecr.ap-south-1.amazonaws.com/co-repo:latest
          echo "::set-output name=image::654400775970.dkr.ecr.ap-south-1.amazonaws.com/co-repo:latest"  
   
