name: CI/CD worlflow for NDSL PAN verification

on:
 push:
    branches: [ main ]
  
jobs:
  build_and_test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
    
      uses: actions/setup-java@v1
      with:
        java-version: 11
        
    - name: Cache the Maven packages to speed up build
      uses: actions/cache@v1
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2    

    - name: Build project with Maven
      run: mvn -B package --file pom.xml
      
  pack_and_deploy:

     runs-on: ubuntu-latest
     needs: [build_and_test]

     steps:
     - uses: actions/checkout@v2
     - uses: actions/setup-java@v2
       with:
         java-version: '11'
         distribution: 'adopt'
     - run: mvn --batch-mode --update-snapshots verify
     - run: mkdir staging && cp target/*.jar staging
     - uses: actions/upload-artifact@v2
       with:
         name: Package
         path: staging   
         
  deploy:
  
      name: Push to EC2 Instance
      runs-on: ubuntu-latest
      needs: [pack_and_deploy]
      
      steps:
      - name: Checkout the code
        uses: actions/checkout@v1
      env:
        SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
        SOURCE: "/home/runner/work/spring-boot-githubactions/spring-boot-githubactions/staging"
        REMOTE_HOST: "ec2-65-0-139-63.ap-south-1.compute.amazonaws.com"
        REMOTE_USER: "ec2-user"
        TARGET: "/home/ubuntu/git-actions"
